version: "3.8"
services:
  # Eureka Server
  eureka-server:
    image: eureka-server
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8762:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_APPLICATION_NAME=discovery-service
      - SERVER_PORT=8761
    networks:
      - my-network
    restart: always

  # Service Task
  servicetask:
    image: servicetask
    build:
      context: ./task-service
      dockerfile: Dockerfile
    ports:
      - "8085:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - my-network
    restart: always

  # Resource Service
  resource-service:
    image: resource-service
    build:
      context: ./resource-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - my-network
    restart: always

  # Service Gestion Projets
  gestionprojets:
    image: gestionprojets
    build:
      context: ./project-service
      dockerfile: Dockerfile
    ports:
      - "8086:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - my-network
    restart: always

  # Gestion Utilisateurs
  gestionutilisateurs:
    image: gestionutilisateurs
    build:
      context: ./Gestion_utilisateurs
      dockerfile: Dockerfile
    ports:
      - "8087:8084"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - my-network
    restart: always
  # Gateway Service
  gateway:
    image: gateway-service
    build:
      context: ./Gateway_service
      dockerfile: Dockerfile
    ports:
      - "8766:8765"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - servicetask
      - resource-service
      - gestionprojets
      - gestionutilisateurs
    networks:
      - my-network
    restart: always
networks:
  my-network:
    driver: bridge
