services:
  # Eureka Server
  eureka-server:
    image: eureka-server:latest
    build:
      context: ./discovery-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=discovery-service
      - SERVER_PORT=8761
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    networks:
      - my-network
    restart: always

  # Gateway Service
  gateway-service:
    image: gateway-service:latest
    build:
      context: ./Gateway_service
    ports:
      - "8765:8765"
    environment:
      - SPRING_APPLICATION_NAME=gateway-service
      - spring.cloud.gateway.routes[0].id=projects
      - spring.cloud.gateway.routes[0].uri=http://service-gestion-projets:8082
      - spring.cloud.gateway.routes[0].predicates[0]=Path=/api/projects/**
      - spring.cloud.gateway.routes[1].id=tasks
      - spring.cloud.gateway.routes[1].uri=http://service-task:8083
      - spring.cloud.gateway.routes[1].predicates[0]=Path=/api/tasks/**
      - spring.cloud.gateway.routes[2].id=resources
      - spring.cloud.gateway.routes[2].uri=http://resource-service:8080
      - spring.cloud.gateway.routes[2].predicates[0]=Path=/api/resources/**
      - spring.cloud.gateway.routes[3].id=users
      - spring.cloud.gateway.routes[3].uri=http://gestionutilisateurs:8084
      - spring.cloud.gateway.routes[3].predicates[0]=Path=/api/users/**
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - my-network
    restart: always

  # MySQL pour Utilisateurs
  mysql-U:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: user_db
    volumes:
      - user_db:/var/lib/mysql
    networks:
      - my-network

  # Gestion Utilisateurs
  gestionutilisateurs:
    image: gestionutilisateurs:latest
    build:
      context: ./Gestion_utilisateurs
    ports:
      - "8084:8084"
    environment:
      - SPRING_APPLICATION_NAME=gestionutilisateurs
      - SERVER_PORT=8084
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-U:3306/user_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=your_password_here
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - mysql-U
    networks:
      - my-network
    restart: always

  # MySQL pour Projets
  mysql-P:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: projets_db2
    volumes:
      - projets_db2:/var/lib/mysql
    networks:
      - my-network

  # Service Gestion Projets
  service-gestion-projets:
    image: projets-service:latest
    build:
      context: ./project-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_APPLICATION_NAME=ServiceGestionProjets
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-P:3306/projets_db2
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=your_password_here
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - mysql-P
    networks:
      - my-network
    restart: always

  # MySQL pour Taches
  mysql-T:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: task_db2
    volumes:
      - task-db2:/var/lib/mysql
    networks:
      - my-network

  # Service Task
  service-task:
    image: servicetask:latest
    build:
      context: ./task-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_APPLICATION_NAME=ServiceTask
      - SERVER_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-T:3306/task_db2
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=your_password_here
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - mysql-T
    networks:
      - my-network
    restart: always

  # MySQL pour Ressources
  mysql-R:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: resource_db2
    volumes:
      - resource_db2:/var/lib/mysql
    networks:
      - my-network

  # Resource Service
  resource-service:
    image: resource-service
    build:
      context: ./resource-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=resource-service
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-R:3306/resource_db2
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=your_password_here
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - mysql-R
    networks:
      - my-network
    restart: always

volumes:
  projets_db2:
  resource_db2:
  task-db2:
  user_db:

networks:
  my-network:
    driver: bridge
